module.exports.descriptors = [
    'Damaged',
    'Collapsed',
    'Broken',
    'Blocked',
    'Dangerous',
    'Hazardous',
    'Cracked',
    'Unsafe',
    'Potholed',
    'Debris-covered',
    'Overgrown',
    'Vandalized',
    'Worn-out',
    'Rough',
    'Uneven',
    'Disrupted',
    'Faulty',
    'Deteriorated'
];

module.exports.places = [
    'Road',
    'Sidewalk',
    'Intersection',
    'Street',
    'Bridge',
    'Traffic Signal',
    'Pedestrian Crossing',
    'Roundabout',
    'Curb',
    'Median',
    'Bus Stop',
    'Pole',
    'Streetlight',
    'Tree',
    'Open Space',
    'Manhole',
    'Drain',
    'Utility Box',
    'Public Park',
    'Plaza'
];

// module.exports.descriptors = [
//     'Forest',
//     'Ancient',
//     'Petrified',
//     'Roaring',
//     'Cascade',
//     'Tumbling',
//     'Silent',
//     'Redwood',
//     'Bullfrog',
//     'Maple',
//     'Misty',
//     'Elk',
//     'Grizzly',
//     'Ocean',
//     'Sea',
//     'Sky',
//     'Dusty',
//     'Diamond'
// ]

// module.exports.places = [
//     'Flats',
//     'Village',
//     'Canyon',
//     'Pond',
//     'Group Camp',
//     'Horse Camp',
//     'Ghost Town',
//     'Camp',
//     'Dispersed Camp',
//     'Backcountry',
//     'River',
//     'Creek',
//     'Creekside',
//     'Bay',
//     'Spring',
//     'Bayshore',
//     'Sands',
//     'Mule Camp',
//     'Hunting Camp',
//     'Cliffs',
//     'Hollow'
// ]
